### ISSUE TITLE
Collator issue prevents compiling with icu-61.1 on Linux.

### ISSUE THREAD

**Issue by archlinuxrussian** [JGRennison/OpenTTD-patches#34]
This is probably already in the works, but I thought it'd wouldn't be harmful to post this anyway. 
Relevant setup: Arch Linux, kernel 4.15.14, running on [testing] repositories (so probably part of the "problem", but those will be published sooner or later anyway). 
The new version for icu (61.1) probably changes a few things. The source tarball as-is won't compile with the newer version, nor would "./configure" fix the issue. Here's the bit that's relevant with freshly-pulled code:

`[SRC] Compiling date_gui.cpp
In file included from /home/luke/Applications/OpenTTD-patches/src/crashlog.cpp:29:0:
/home/luke/Applications/OpenTTD-patches/src/language.h:108:8: error: ‘Collator’ does not name a type; did you mean ‘UCollator’?
 extern Collator *_current_collator;
        ^~~~~~~~
        UCollator
[SRC] Compiling debug.cpp
make[1]: *** [Makefile:239: crashlog.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/luke/Applications/OpenTTD-patches/objs/release'
make: *** [Makefile:57: all] Error 1
`

As I said, you're probably already aware of this, but I thought I'd post it anyway. I also see I posted something similar before about icu, so hopefully this isn't just more noise ^_^ thanks anyway! And if there's any way I can help or any information you want or need, I'd be happy to provide it.

**Comment by HanFox** [comment]
Is this not the same problem as what has been recently fixed in the main Arch repos?

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/openttd#n20

**Comment by HanFox** [comment]
Okay, I have no idea why I ask "is this the problem" instead of just testing myself...

Indeed invoking the `CXXFLAGS+=' -DU_USING_ICU_NAMESPACE=1'` does allow the build to work with icu61.1.

**Comment by archlinuxrussian** [comment]
Ah, that should be it. And pardon me for asking, but where should that invocation be? As an environment variable, in the make file or...just asking since I usually just "git pull && make" occasionally.

**Comment by HanFox** [comment]
I believe you can add it to the configure or make command ala: https://stackoverflow.com/a/23407800

Alternatively you can use the AUR package I quietly maintain: https://aur.archlinux.org/packages/openttd-jgrpp

**Comment by archlinuxrussian** [comment]
Thanks! I assume a hardfix will be done later :) but I appreciate the help!...I guess I'll close the issue now eh?

**Comment by JGRennison** [comment]
A proper fix may take some time, unless trunk decide to implement one.
I will look into it when time permits.
